### ISSUE TITLE
run using gem exec?

### ISSUE THREAD

**Issue by indirect** [testdouble/gem_dating#5]
Have you considered suggesting users run `gem exec gem_dating` so they can just use the tool without any gemfile shenanigans?

**Comment by stevenjackson** [comment]
I think that's interesting and a neat way to avoid the Gemfile bits.  Seems like we could at least add it to the README as an option.  I'm unsure if there's a lot of overlap between "I found this 9 year old Gemfile" and "I have a recent version of rubygems installed", but it shouldn't hurt and can only get better :)
